dependencies {
    api project(":hammer-api")
    
    api group: 'cn.featherfly.common', name: 'common-spring', version: '0.4.2'
    api group: 'cn.featherfly.common', name: 'common-asm', version: '0.4.0-SNAPSHOT'
    //api group: 'cn.featherfly.common', name: 'common-tuple', version: '1.0.0'
    api group: 'cn.featherfly.constant', name: 'constant-core', version: '1.6.9'
	api group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.20.1'
    api group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.20.1'
    api group: 'org.freemarker', name: 'freemarker', version: '2.3.34'
    
    // 3.2 去掉了DefineClassHelper，未找到替代实现前暂不升级
    // api group: 'org.objenesis', name: 'objenesis', version: '3.1'
	//api group: 'org.javassist', name: 'javassist', version: '3.27.0-GA'
	//api group: 'net.bytebuddy', name: 'byte-buddy', version: '1.10.18'
	//api group: 'org.ow2.asm', name: 'asm', version: '9.0'
	//api group: 'org.ow2.asm', name: 'asm-tree', version: '9.0'
	//api group: 'org.ow2.asm', name: 'asm-util', version: '9.0'
	//api group: 'org.ow2.asm', name: 'asm-common', version: '9.0'
	//api group: 'org.ow2.asm', name: 'asm-debug-all', version: '5.2'
	
	implementation 'javax.persistence:javax.persistence-api:2.2'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.2.0'
	    
    // validation
    testImplementation 'cn.featherfly.validation:javax.validation-api:0.3.0'
    testImplementation group: 'org.glassfish', name: 'javax.el', version: '3.0.0' // hibernate-validator 需要使用 
    testImplementation group: 'org.hibernate.validator', name: 'hibernate-validator', version: '6.2.5.Final'

    //implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
	implementation group: 'org.springframework', name: 'spring-context', version: sv
		
//	testImplementation project(":hammer-api")
	testImplementation group: 'cn.featherfly.common', name: 'common-db', version: '0.7.1'
	testImplementation group: 'org.ow2.asm', name: 'asm-util', version: '9.0'
	testImplementation group: 'org.springframework', name: 'spring-core', version: '5.3.14'
	testImplementation group: 'org.springframework', name: 'spring-core', version: '5.3.14'
	
}